"use server";

import {revalidatePath} from "next/cache";

import {collections} from "../db/collections";
import {customerInputSchema} from "../db/schemas/customers";

export type ActionResult<T = unknown> = {ok: true; data: T} | {ok: false; error: string};

export async function createCustomer(formData: FormData): Promise<ActionResult<{id: string}>> {
  const raw = {
    agencyOrgId: String(formData.get("agencyOrgId") ?? ""),
    name: String(formData.get("name") ?? ""),
    contactName: String(formData.get("contactName") ?? ""),
    contactEmail: String(formData.get("contactEmail") ?? ""),
    industry: String(formData.get("industry") ?? ""),
    city: String(formData.get("city") ?? ""),
    plan: String(formData.get("plan") ?? "Starter"),
    status: String(formData.get("status") ?? "Onboarding"),
    mrrCents: Number(formData.get("mrrCents") ?? 0),
  };

  const parsed = customerInputSchema.safeParse(raw);

  if (!parsed.success) {
    return {ok: false, error: parsed.error.issues.map((i) => i.message).join("; ")};
  }

  const c = await collections.customers();
  const now = new Date();
  const {insertedId} = await c.insertOne({
    ...parsed.data,
    avatar: parsed.data.avatar ?? null,
    sites: parsed.data.sites ?? 0,
    keywords: parsed.data.keywords ?? 0,
    health: parsed.data.health ?? 80,
    joinedAt: now,
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
    // _id auto-generated by Mongo
  } as never);

  revalidatePath("/white-label/customers");
  revalidatePath("/white-label");

  return {ok: true, data: {id: insertedId.toHexString()}};
}
