import { z } from "zod"
import {
  CoreContentSchema,
  CoreFaqItemSchema,
} from "./core-content"
import type { CoreServiceItem, CoreFaqItem } from "./core-content"

/**
 * Strict JSON schema for titan-default template output.
 * Extends Core with dynamic service detail pages and city/area SEO pages.
 *
 * Slug discipline:
 *   - servicePages[].slug and cityPages[].slug are generated by code BEFORE
 *     the LLM call and passed in the prompt. The model must echo them back
 *     exactly — it must not invent slugs.
 */

// ─── Service detail page ──────────────────────────────────────────────────────

export const TitanServicePageSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens").describe("URL slug — echo back exactly as provided"),
  headline: z.string().describe("Page headline, 5-12 words"),
  intro: z.string().describe("Service intro, 40-80 words"),
  benefits: z.array(
    z.object({
      title: z.string().describe("Benefit title, 2-5 words"),
      description: z.string().describe("Benefit description, 15-30 words"),
    }),
  ).min(3).max(5),
  process: z.array(
    z.object({
      step: z.number().int().min(1),
      title: z.string().describe("Step title, 2-5 words"),
      description: z.string().describe("Step description, 15-30 words"),
    }),
  ).min(2).max(5),
  faq: z.array(CoreFaqItemSchema).min(2).max(4),
  relatedServices: z.array(z.string()).max(3).describe("Slugs of related service pages"),
  seo: z.object({
    title: z.string().max(60).describe("Page title tag, under 60 chars"),
    description: z.string().max(160).describe("Meta description, under 160 chars"),
  }),
})

// ─── City/area SEO page ───────────────────────────────────────────────────────

export const TitanCityPageSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens").describe("URL slug — echo back exactly as provided"),
  city: z.string().describe("City/area name as it appears in copy"),
  headline: z.string().describe("Page headline mentioning city, 5-12 words"),
  intro: z.string().describe("City-specific intro, 40-80 words, mentions location naturally"),
  serviceHighlights: z.array(
    z.object({
      title: z.string().describe("Service name, 2-5 words"),
      description: z.string().describe("City-specific service description, 20-40 words"),
    }),
  ).min(2).max(4),
  localSignals: z.array(z.string().describe("Local trust signal, 10-25 words")).min(2).max(4),
  seo: z.object({
    title: z.string().max(60).describe("Page title tag, under 60 chars, includes city name"),
    description: z.string().max(160).describe("Meta description, under 160 chars, includes city name"),
  }),
})

// ─── Root schema ──────────────────────────────────────────────────────────────

export const TitanContentSchema = CoreContentSchema.extend({
  servicePages: z.array(TitanServicePageSchema)
    .min(1)
    .max(12)
    .describe("One page per service in offeredServices"),
  cityPages: z.array(TitanCityPageSchema)
    .min(1)
    .max(20)
    .describe("One page per city in serviceAreas"),
})

export type TitanContent = z.infer<typeof TitanContentSchema>
export type TitanServicePage = z.infer<typeof TitanServicePageSchema>
export type TitanCityPage = z.infer<typeof TitanCityPageSchema>

// Re-export shared types used by Titan
export type { CoreServiceItem, CoreFaqItem }
